
from __future__ import print_function
import os
import unittest
from molbiox.algor.translate import CodonTable
from molbiox.frame.signature import Sig
from molbiox.frame.regexon import Regexon
from molbiox.kb.translate import get_transl_table

sub = Regexon.new(r'[^a-zA-Z]', '')

test_data = {
    'dna': """
    TTGATGGCTAAGAGTAAAATCTTAAAAAACACACTGGTTCTATATTTTCGTCAAGTTTTG
    ATTGTATTAATTACTCTCTATTCAATGAGAGTTGTATTAAATGAATTAGGTGTGGATGAT
    TTTGGTATTTATAGCGTTGTGGCTGGTTTTGTAACTTTACTTGCATTTTTACCCGGAAGC
    ATGGCGAGTGCAACGCAGCGGTTTTTCTCTTTTGCGATGGGGAAATCGGATATAGTAAAA
    TTAAAGCAAACCTTCAGTGTTAATTTAGTTATGTATACTGGCATAGCCTTGTTAGCATAT
    ATAACATTTCAAACTATCGGATTTTGGTATGTTGATGAATATCTAAAAATACCTCATAAC
    CGCTTTCATGCAGCCTTGGAATTATATCACTATGTGTCTTTATCATTTATTTTTTCAATT
    TTTTCTGCGCCTTTTATCGCGATTTTAATTGCGCACGAAGATATGCACATTTATGCGATC
    TTCTCGGTTTTTGATGCATTTTTAAAACTAGTAGCCGCAATTTCTTTAGACTATGTGAAC
    TATGATTTGTTAGCTTATTATGGAGTGGCTCTTTTGATTGTATCTGGATTGCTTGCTTTC
    GCGTATATTTTTATATGTATAAAGAAATATCCAGAGTGTCAAATGAAAAAGCTTTATTGG
    AGTTCGAGTATACTGAAAGAAATTATTGGTTTCACGATATGGACTTTGCTAGGTCAATTG
    AGCACTGTTTTTAGAAATCAGGCAGTAACTGTTCTTGTAAACCAAATGTTTAATCCTTCA
    ATTGTGGCAGCTCGTGCAATTGCCTTGAATGTGGCTAGTCAAGTTGGAATTTTTTCGAAT
    AATTTAAATACAGGGTTATATCCACCAATTATAAAAGCTTACGCAGCAAATCAAAAAGAG
    GAAATGCTGAGTTTAGTTTTTAATGGTTCTAAACTGACTTTCTTCTTGATGTGGGTATGT
    GCATTACCCATGTTGCTTGAAATGGAAACGATATTAACACTTTGGCTAAAAACACCACCA
    TCAGAAGCGATATTATTTACTCAGTTAGCGATTGTTGAATCCTTGATACTGGCTATAAGC
    ATGCCTTTAACTACTGCGGCAAGAGCACCAGGGAAAATGGCGTTGTATGAAATAATTCTA
    GGCGCCATTCAAATAGCAATATTTTTTGTTTCATGGTGGTTTCTGAAATTTGGTTATTCT
    GCTGAATGGGTTTTCTACATAGCAATAGCGGCTAATATTATTATGTTTAAAGTTCGCTTG
    TTATTAGTAAGCTATTTAACTGATCTTCCTGTAATGGCTTATTATCAAAGAGTTGTAGTT
    CCGGTTTTATCTGTTCTGGTTATTTCATCATTATCTAGTATCTTGCTATTGAACAACTTA
    CCAAGAAATTTAGGTGCATCTTTATTGGTGATTATTTTTTCTATCGGTGTTTCGATATTG
    ACAATGTACTTCTTAGGCTTAGATAAGTACTGGCGTGAAAAAGTGGTCGGTGTGCTAACC
    AGTAAATTTTTAAAATCTAGAGAGGTGCGATGA""" | sub,
    'protein': """
    LMAKSKILKNTLVLYFRQVLIVLITLYSMRVVLNELGVDDFGIYSVVAGFVTLLAFLPGSMASATQRFFS
    FAMGKSDIVKLKQTFSVNLVMYTGIALLAYITFQTIGFWYVDEYLKIPHNRFHAALELYHYVSLSFIFSI
    FSAPFIAILIAHEDMHIYAIFSVFDAFLKLVAAISLDYVNYDLLAYYGVALLIVSGLLAFAYIFICIKKY
    PECQMKKLYWSSSILKEIIGFTIWTLLGQLSTVFRNQAVTVLVNQMFNPSIVAARAIALNVASQVGIFSN
    NLNTGLYPPIIKAYAANQKEEMLSLVFNGSKLTFFLMWVCALPMLLEMETILTLWLKTPPSEAILFTQLA
    IVESLILAISMPLTTAARAPGKMALYEIILGAIQIAIFFVSWWFLKFGYSAEWVFYIAIAANIIMFKVRL
    LLVSYLTDLPVMAYYQRVVVPVLSVLVISSLSSILLLNNLPRNLGASLLVIIFSIGVSILTMYFLGLDKY
    WREKVVGVLTSKFLKSREVR""" | sub,
} + Sig('', cheat=0)


def test_translate():
    dic = get_transl_table()
    codontab = CodonTable(dic)
    assert len(test_data['dna']) % 3 == 0
    protein = codontab.translate(test_data['dna']).decode('ascii')
    print(protein)
    print(test_data['protein'])
    assert protein[:-1] == test_data['protein']
    assert protein[-1] == '*'
