#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals, print_function

import argparse
from molbiox.tolerant import safe_bracket
from molbiox.info.protnames import lps_gene_prot_map


ext = '.protname'


def get_prot_name(line):
    items = line.split(maxsplit=7)
    gname = items[5]
    pname = safe_bracket(items, 7) or lps_gene_prot_map.get(gname) or '-'
    return pname


if __name__ == '__main__':
    desc = 'MBX Script'
    parser = argparse.ArgumentParser(description=desc)

    parser.add_argument(
        '--rude', action='store_true',
        help='overwriting existing files if needed')

    parser.add_argument(
        'filenames', metavar='DATA-file', nargs='+',
        help='an input data file')

    args = parser.parse_args()

    for filename in args.filenames:
        filename_out = filename + ext

        infile = open(filename)
        outfile = open(filename_out, 'w')

        title = infile.readline().strip()[1:]
        for line in infile:
            line = line.strip()
            key = line.split()[0] + '.' + title
            pname = get_prot_name(line)
            print(key, pname, sep='\t', file=outfile)

        infile.close()
        outfile.close()
