#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals
import sys

from molbiox.locate import locate_template


templates = {
    'test':     's.mbxtest.py',
    'blast':    's.blast.sh',
    'blastfmt':    's.blast-formatter.sh',
    'velvet':   's.velvet.sh',
    'python':   's.script.py',
    'glimmer':  's.glimmer.sh',
    'hmmscan':  's.hmmscan.sh',

    'pred-sql': 'd.feat-create.sql',

    'py-decorator': 'x.decorator.py',

    'lgrouper': 's.lgrouper.py',
}


if len(sys.argv) == 1:
    for k in templates:
        print(k)
    exit(0)
else:
    key = sys.argv[1]

tpl_path = locate_template(templates.get(key, 's.script.py'))
tpl = open(tpl_path).read()

print(tpl)

