#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals
import sys
import os
import re

from molbiox.io import fasta
from molbiox.io import genbank

if len(sys.argv) == 1:
    # TODO: print help
   sys.exit('too few arguments')
elif len(sys.argv) == 2:
    infile = open(sys.argv[1])
    outfile = sys.stdout
elif len(sys.argv) == 3:
    infile = open(sys.argv[1])
    if os.path.exists(sys.argv[2]):
        exit('output file already exists')
    outfile = open(sys.argv[2])
else:
    # TODO: print help
    sys.exit('too many arguments')

seqdicts = genbank.read_sequences(infile)
fasta.write(outfile, seqdicts)
