#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals, print_function

import sys

from molbiox.io import fasta


for filename in sys.argv[1:]:
    try:
        for seqrecord in fasta.read(filename):
            fasta.write(sys.stdout, seqrecord)
    except:
        print('fail: {}'.format(filename), file=sys.stderr)
