#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals, print_function

import argparse
from molbiox.io import fasta

# TODO: --interactive mode: ask user for gap size

EXT = '.n-join.fas'

if __name__ == '__main__':
    desc = 'Join sequences with N+'
    parser = argparse.ArgumentParser(description=desc)

    parser.add_argument(
        '--rude', action='store_true',
        help='overwriting existing files if needed')

    parser.add_argument(
        '--size', type=int, default=300,
        help='number of Ns to pad')

    parser.add_argument(
        '--extkeep', action='store_true',
        help='keep original file extension in new filename(s)')

    parser.add_argument(
        'filenames', metavar='DATA-file', nargs='+',
        help='an input data file')

    args = parser.parse_args()

    for filename in args.filenames:
        if args.extkeep:
            filename_new = filename + EXT
        else:
            filename_new = fasta.fix_filename(filename, suffix=EXT)

        outfile = open(filename_new, 'w')

        sequences = (r['seq'] for r in fasta.read(filename))
        sequencej = (args.size*'N').join(sequences)
        record = dict(seq=sequencej, cmt=filename)
        fasta.write(outfile, record)
