#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals, print_function

import argparse


def parse(filename, sep=None):
    """ Parse a text file as a set """
    return set(l.strip() for l in open(filename))


def calc(operator, sets):
    result = next(sets)

    for sv in sets:
        if not sv:
            continue
        if operator == '-':
            result -= sv
        elif operator == 'u':
            result |= sv
        elif operator == 'n':
            result &= sv
        else:
            pass
        if not result:
            break
    return result


if __name__ == '__main__':
    
    desc = 'Calculate set operation set1 - set2 - set3 - ...'
    argparser = argparse.ArgumentParser(description=desc)

    argparser.add_argument(
        'operator', choices=['u', 'n', '-'],
        help='u for union, n for intersection, - for minus')

    argparser.add_argument(
        'filenames', metavar='filename', nargs='+',
        help='input files')

    args = argparser.parse_args()
    sets = (parse(fn) for fn in args.filenames)
    result = calc(args.operator, sets)

    for x in result:
        print(x)
