#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals

import argparse
import hashlib
import sys

from molbiox.frame.compat import unistr
from molbiox.io import fasta

ext_hseq = '.h-seq'
ext_htab = '.h-tab'


def hash_sequence(sequence):
    if isinstance(sequence, unistr):
        s = sequence.upper().encode('ascii')
    else:
        s = sequence.upper()
    return hashlib.sha1(s).hexdigest()


def hdump(htab_file, hseq_file, seqrecords, filename=None):
    for sr in seqrecords:
        hv = hash_sequence(sr['seq'])
        if htab_file:
            if filename:
                l = '{}\t{}\t{}\n'.format(hv, filename, sr['cmt'])
            else:
                l = '{}\t{}\n'.format(hv, sr['cmt'])
            htab_file.write(l)
        if hseq_file:
            sr['cmt'] = 'sha1-' + hv
            fasta.write(hseq_file, sr)


if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='Calculate hashsums of sequences')

    parser.add_argument(
        'filenames', metavar='FASTA-file', nargs='+',
        help='a FASTA-file containing 1 or multiple sequences')

    parser.add_argument(
        '--htab', action='store_true',
        help='save hash-comment table to files ({})'.format(ext_htab))

    parser.add_argument(
        '--hseq', action='store_true',
        help='save hash-commented FASTA-files ({})'.format(ext_hseq))

    parser.add_argument(
        '--hdump', action='store_true',
        help='equivolent to "--hseq --htab"')

    parser.add_argument(
        '--extkeep', action='store_true',
        help='keep original file extension in new filename(s)')

    parser.add_argument(
        '--wfname', action='store_true',
        help='with filename, i.e. output hash-filename-cmt table')

    args = parser.parse_args()
    dump_htab = args.htab or args.hdump
    dump_hseq = args.hseq or args.hdump

    for name in args.filenames:
        if args.extkeep:
            htab_filename = name + ext_htab
            hseq_filename = name + ext_hseq
        else:
            htab_filename = fasta.fix_filename(name, suffix=ext_htab)
            hseq_filename = fasta.fix_filename(name, suffix=ext_hseq)

        # .h-tab or STDOUT
        if dump_htab:
            htab_file = open(htab_filename, 'w')
        else:
            htab_file = sys.stdout

        # .h-seq or not
        if dump_hseq:
            hseq_file = open(hseq_filename, 'w')
        else:
            hseq_file = None

        seqrecords = fasta.read(name)
        if args.wfname:
            hdump(htab_file, hseq_file, seqrecords, name)
        else:
            hdump(htab_file, hseq_file, seqrecords, None)




