#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals, print_function

import argparse
from molbiox.io import fasta
from molbiox.io import primer


def _():
    pass

ext = '.primer3'


if __name__ == '__main__':

    desc = 'MBX Script'
    parser = argparse.ArgumentParser(description=desc)

    parser.add_argument(
        '--rude', action='store_true',
        help='overwriting existing files if needed')

    parser.add_argument(
        'filename', metavar='FASTA-file', nargs='?',
        help='a FASTA data file')

    args = parser.parse_args()

    # for filename in args.filenames:
    #     filename_out = filename + ext
    texts = []

    for r in fasta.read(args.filename):
        text = primer.gen_primer3_input(cmt=r.cmt, seq=r.seq)
        if not text.endswith('\n'):
            text += '\n'
        texts.append(text)
        # name = r.cmt.split()[0]

    open(args.filename + ext, 'w').write(''.join(texts))
