#!/usr/bin/env python3

import os
import sys
from molbiox import initMBXpdir

if __name__ == "__main__":
    try:
        path = initMBXpdir()
        print(path)
    except FileExistsError as err:
        print(err, file=sys.stderr) 


