#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals, print_function

import argparse


def get_blast_cols(name):
    if name == 'mini':
        from molbiox.iofmt.blast import fieldlist_mini
        from molbiox.info.ncbi import blast_fieldmap
        return [blast_fieldmap[k[0]] for k in fieldlist_mini]
    elif name == 'all':
        from molbiox.iofmt.blast import fieldlist_all
        from molbiox.info.ncbi import blast_fieldmap
        return [blast_fieldmap[k[0]] for k in fieldlist_all]
    else:
        from molbiox.iofmt.blast import fieldlist_default
        from molbiox.info.ncbi import blast_fieldmap
        return [blast_fieldmap[k[0]] for k in fieldlist_default]



if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='Get miscellaneous info')

    parser.add_argument('command', metavar='COMMAND')

    args = parser.parse_args()

    if args.command == 'blast-mini':
        print(' '.join(get_blast_cols('mini')))
    if args.command == 'blast-all':
        print(' '.join(get_blast_cols('all')))
