#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals
import sys

from molbiox.io import glimmer

ifilename = sys.argv[1]
ofilename = sys.argv[2]

predicts = glimmer.read_g3_predict(ifilename)
predicts = list(predicts)

glimmer.write_g3_mcoordz(ofilename, predicts)
