#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals, print_function

import sys
import argparse
from collections import Counter

from molbiox.io import fasta


# DEPRECATED!!
# replaced by mbx-seq-info -a type some.fa


if __name__ == '__main__':

    desc = 'Test whether a FastA file contains protein or nucleotides'
    parser = argparse.ArgumentParser(description=desc)

    parser.add_argument(
        'filename', metavar='FASTA-file',
        help='a FASTA-file containing 1 or multiple sequences')

    args = parser.parse_args()

    sequence = fasta.readseq(args.filename)
    counter = Counter(sequence.lower())

    if sum(counter[k] for k in 'atgcn') >= len(sequence) * .6:
        print('nucl')
    else:
        print('prot')
