#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals, print_function

import argparse
from jinja2 import Template

from molbiox.iofmt import glimmer
from molbiox.locate import locate_template


tpl_path = locate_template('d.feat-insert-glimmer3.sql')
tpl = Template(open(tpl_path).read())


if __name__ == '__main__':
    desc = 'MBX Script'
    parser = argparse.ArgumentParser(description=desc)

    parser.add_argument(
        'filenames', metavar='DATA-file', nargs='+',
        help='an input data file')

    args = parser.parse_args()

    for filename in args.filenames:
        # assume the first dot-split part to be strain
        strain = filename.split('.')[0]
        records = glimmer.read_g3_predict(filename)
        res = tpl.render(records=records, table='mbz_t1_features', strain=strain)
        print(res)

