#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals
import sys

from collections import OrderedDict

from molbiox.iofmt import fasta

filename_fasta = sys.argv[1]
filename_keys = sys.argv[2]

keys = [l.split()[0] for l in open(filename_keys) if l.strip()]
selection = OrderedDict((k, None) for k in keys)

for seqrecord in fasta.read(filename_fasta):
    # use title.split()[0] to be tolerent to titles with description
    cmt = seqrecord['cmt'].split()[0]
    if cmt in selection:
        selection[cmt] = seqrecord['seq']

for cmt, seq in selection.items():
    if seq:
        seqrecord = dict(cmt=cmt, seq=seq)
        fasta.write(sys.stdout, seqrecord)
