#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals, print_function

import os
import sys
import argparse
import stat



from molbiox.locate import locate_template


templates = {
    'test':         's.mbxtest.py',
    'blast':        's.blast.sh',
    'blastfmt':     's.blast-formatter.sh',
    'velvet':       's.velvet.sh',
    'python':       's.script.py',
    'glimmer':      's.glimmer.sh',
    'hmmscan':      's.hmmscan.sh',
    'muscle':       's.muscle.sh',
    'tmhmm':       's.tmhmm.sh',

    'pred-sql': 'd.feat-create.sql',

    'py-decorator': 'x.decorator.py',
    'lgrouper': 's.lgrouper.py',
}


if __name__ == '__main__':

    desc = 'Generate template script'
    parser = argparse.ArgumentParser(description=desc)

    parser.add_argument(
        '--rude', action='store_true',
        help='overwriting existing files if needed')

    parser.add_argument(
        'template', default='test',
        help='name of template to start from')

    parser.add_argument(
        'filename', default='-', nargs='?',
        help='path to the output file, default STDOUT')

    args = parser.parse_args()

    tpl_path = locate_template(templates.get(args.template, 's.script.py'))
    tpl = open(tpl_path).read()

    if args.filename == '-':
        sys.stdout.write(tpl)
    else:
        if not args.rude and os.path.exists(args.filename):
            message = 'Fail: "{}" exists already'.format(args.filename)
            print(message, file=sys.stderr)
            sys.exit()

        outfile = open(args.filename, 'w')
        outfile.write(tpl)
        outfile.close()

        # chmod +x
        st = os.stat(args.filename)
        os.chmod(args.filename, st.st_mode | stat.S_IEXEC)
