#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals, print_function

import os
import sys
import argparse

from molbiox.iofmt import fasta
from molbiox.iofmt import genbank


ext_nts = '.fas'


if __name__ == '__main__':

    desc = 'Extract DNA sequences from genbank files'
    parser = argparse.ArgumentParser(description=desc)

    parser.add_argument(
        '--rude', action='store_true',
        help='overwriting existing files if needed')

    parser.add_argument(
        'filenames', metavar='GenBank-file', nargs='+',
        help='genbank files to extract sequences from')

    args = parser.parse_args()

    for filename in args.filenames:
        filename_out = filename + ext_nts
        if not args.rude and os.path.exists(filename_out):
            message = 'Fail: "{}" exists already'.format(filename_out)
            print(message, file=sys.stderr)
            continue

        seqrecords = genbank.read_sequences(filename)

        outfile = open(filename_out, 'w')
        fasta.write(outfile, seqrecords)
