#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals, print_function

import argparse



if __name__ == '__main__':
    
    desc = 'Calculate set operation set1 - set2 - set3 - ...'
    parser = argparse.ArgumentParser(description=desc)

    parser.add_argument(
        'filenames', metavar='DATA-file', nargs='+',
        help='an input data file')

    args = parser.parse_args()

    result = set(l.strip() for l in open(args.filenames[0]))

    for filename in args.filenames[1:]:
        sub = set(l.strip() for l in open(filename))
        if not sub:
            continue
        result -= sub
        if not result:
            break


