#!/usr/bin/env python3
# coding: utf-8

from __future__ import unicode_literals, print_function

import sys
import re
import argparse

from molbiox.iofmt import fasta


if __name__ == '__main__':

    desc = 'Concatenate FASTA-files with reformatting'
    parser = argparse.ArgumentParser(description=desc)

    parser.add_argument(
        'filenames', metavar='FASTA-file', nargs='+',
        help='a FASTA-file containing 1 or multiple sequences')

    args = parser.parse_args()

    for filename in args.filenames:
        try:
            for seqrecord in fasta.read(filename):
                fasta.write(sys.stdout, seqrecord)
        except:
            print('fail: {}'.format(filename), file=sys.stderr)
